import { Gift, PokerChip, Wallet, GameController } from "phosphor-react";

export const navItems = (t) => [
  {
    icon: <PokerChip className="mr-1" size={20} />,
    class: "sub-casinos",
    label: t('Casinos ▼'),
    href: "/casinos",
    subMenu: [
      { label: t("Crypto Casinos"), href: "/crypto-casinos" },
      { label: t('Fast Withdrawal Casinos'), href: "/fast-withdrawal-casinos" },
      { label: t('Live Casinos'), href: "/live-casinos" },
      { label: t('Newest Casinos'), href: "/newest-casinos" },
      { label: t('Top Certified Casinos'), href: "/top-certified-casinos" },
      { label: t('Top Sports Casinos'), href: "/top-sports-casinos" },
    ],
  },
  {
    icon: <Gift className="mr-1" size={20} />,
    class: "sub-bonuses",
    label: t("Bonuses ▼"),
    href: "/bonuses",
    subMenu: [
      // { label: t("No Deposit Bonuses"), href: "/no-deposit-bonuses" },
      { label: t("Exclusive Bonuses"), href: "/exclusive-bonuses" },
      { label: t("Deposit Bonuses"), href: "/deposit-bonuses" },
      { label: t("Welcome Bonuses"), href: "/welcome-bonuses" },
      // { label: t("No Wagering Bonuses"), href: "/no-wagering-bonuses" },
    ],
  },
  {
    icon: <Wallet className="mr-1" size={20} />,
    class: "sub-payments",
    label: t("All Payments ▼"),
    href: "/payments",
    subMenu: [
      { label: t("Apple Pay"), href: "/payments/apple-pay" },
      { label: t("Bitcoin"), href: "/payments/bitcoin-casino" },
      { label: t("Ecopayz"), href: "/payments/ecopayz" },
      { label: t("Maestro"), href: "/payments/maestro" },
      { label: t("Mastercard"), href: "/payments/mastercard" },
      { label: t("Mobile Payments"), href: "/payments/mobile-payments" },
      { label: t("Muchbetter"), href: "/payments/muchbetter" },
      { label: t("Neosurf"), href: "/payments/neosurf" },
      { label: t("Neteller"), href: "/payments/neteller-casino" },
      { label: t("PayPal"), href: "/payments/paypal-casino" },
      { label: t("Paysafecard"), href: "/payments/paysafecard-casino" },
      { label: t("Pix"), href: "/payments/pix" },
      { label: t("Skrill"), href: "/payments/skrill-casino" },
      { label: t("Trustly"), href: "/payments/trustly" },
      { label: t("Visa"), href: "/payments/visa" },
    ],
  },
  {
    icon: <GameController className="mr-1" size={20} />,
    class: "sub-providers",
    label: t("Game Providers ▼"),
    href: "/game-providers",
    subMenu: [
      { label: t("Amatic"), href: "/game-providers/amatic" },
      { label: t("BGaming"), href: "/game-providers/bgaming" },
      { label: t("Boongo"), href: "/game-providers/boongo" },
      { label: t("Amusnet"), href: "/game-providers/amusnet" },
      { label: t("Evolution"), href: "/game-providers/evolution" },
      { label: t("Mascot"), href: "/game-providers/mascot" },
      { label: t("NeTent"), href: "/game-providers/netent" },
      { label: t("Nolimit city"), href: "/game-providers/nolimit-city" },
      { label: t("Play’n go"), href: "/game-providers/playn-go" },
      { label: t("Pragmatic Play"), href: "/game-providers/pragmatic-play" },
      { label: t("Push Gaming"), href: "/game-providers/push-gaming" },
      { label: t("Spinomenal"), href: "/game-providers/spinomenal" },
    ],
  },
];
